### ISSUE TITLE
How to add change log in email using this plugin coperating with email-ext-plugin

### ISSUE THREAD

**Issue by zelongg** [paulwellnerbou/git-changelog-jenkins-plugin#4]
When I launch a build, I can see the changes in Jenkins.

Could I use this git-changelog-plugin to add changes in email?

<img width="1437" alt="screen shot 2016-11-02 at 1 16 14 pm" src="https://cloud.githubusercontent.com/assets/21305437/19917599/81a4dbf2-a0ff-11e6-8fdd-2fde2516f688.png">

**Comment by paulwellnerbou** [comment]
Yes, you can.

Actually git-changelog-plugin consists of two separated plugins doing very similar stuff, my part and @tomasbjerre's part (the latter is more used than mine).

It is possible to publish the changelog with my part of the plugin via email (that was my original intent for writing this plugin). There is a short documentation on how to do it in the github's README of this project, see https://github.com/jenkinsci/git-changelog-plugin#using-as-token-macro-replacement-provider

By the way, please use the official jenkins repo for issues on this plugin: https://github.com/jenkinsci/git-changelog-plugin

**Comment by paulwellnerbou** [comment]
For further discussions and bugs, use https://github.com/jenkinsci/git-changelog-plugin, please.

**Comment by gongzelong0718** [comment]
Marked
