### ISSUE TITLE
Html incorrectly rendered in summary on job page

### ISSUE THREAD

**Issue by vivelys** [paulwellnerbou/git-changelog-jenkins-plugin#5]
Hello,
I used the same template for both printing a summary on job page and create file (the one found [here](https://github.com/tomasbjerre/git-changelog-lib/blob/master/examples/changelog_html.mustache)).
The file is created but when I open the job page, all html tag are visible and no rendering is done.
If I add to the a description using html tag, the description is rightly rendered.
![2017-03-22 23_14_17-smtpservice 1 11 6290 18 jenkins](https://cloud.githubusercontent.com/assets/10617428/24223225/7b37c364-0f55-11e7-842a-87a5757184d4.png)
 
Any idea ?
Thank you

**Comment by paulwellnerbou** [comment]
Could you give a few more details of your configuration? Which Post-Action are you using?

**Comment by vivelys** [comment]
I'm using Git Changelog plugin 1.45 on Jenkins 2.51 (Windows server 2008 R2) with the following plugin settings : (full copy paste from the sample to be sure I didn't make any mistake)
![2017-03-24 08_37_28-smtpservice config jenkins](https://cloud.githubusercontent.com/assets/10617428/24284818/76a50bc2-106d-11e7-90cf-0ff8962258cb.png)

**Comment by vivelys** [comment]
Any idea ?

**Comment by paulwellnerbou** [comment]
That is part of @tomasbjerre's plugin part.
For further discussions and bugs, use https://github.com/jenkinsci/git-changelog-plugin, please.
