### ISSUE TITLE
FileNotFoundException when specifying Output file for Post Build Action

### ISSUE THREAD

**Issue by sparack** [paulwellnerbou/git-changelog-jenkins-plugin#6]
When i specify an output file name - for post build action - it gives me permission denied on jenkins - saying java.io.FileNotFoundException: change.log (Permission denied)

I even tried first creating that file by executing shell - touch change.log and in the output file I specified $WORKSPACE/change.log - but that did not work either

Any suggestions? Thanks

**Comment by bestimmaa** [comment]
same here

**Comment by paulwellnerbou** [comment]
I would need more configuration details to track this down.
For further discussions and bugs, use https://github.com/jenkinsci/git-changelog-plugin, please.
